### ISSUE TITLE
How to use this plugin correctly?

### ISSUE THREAD

**Issue by jreimone** [jenkinsci/junit-attachments-plugin#4]
I would like to use this plugin but just nothing happens when I add a System.out with the appropriate syntax. Here you can see what System.out's I generate in my test runs:

http://hudson-st.inf.tu-dresden.de:8080/view/Refactory%20Stuff/job/GUERY%20DSL%20and%20Tests/171/testReport/org.modelrefactoring.guery.test/MotifSolvingAndSaveTest/testAndGenerateRoleMappings_MM___bpmn2___RM___ExtractSubX___MPL___1___MR___1_000_000_/?

How to use this plugin correctly?

**Comment by jglick** [comment]
Please use JIRA.
