### ISSUE TITLE
Parse <error> and <failure> tags as well

### ISSUE THREAD

**Issue by florianpilz** [jenkinsci/junit-attachments-plugin#6]
Currently, just the tags `<system-out>` and `<system-err>` are parsed to look for attachments. I propose search in `<error>` and `<failure>` tags as well, because when using a different test runner, it may use the tags differently.

To give a concise example: We are using the zope.testrunner to test our Python projects. The generated XML uses the same tags as allowed by JUnit Test Cases, however, errors and tracebacks are written to `<error>` and `<failure>`, thus the problem.

**Comment by jglick** [comment]
Please use JIRA.
