### ISSUE TITLE
Publishing does not work for a sub-projects

### ISSUE THREAD

**Issue by artemonster** [jenkinsci/junit-attachments-plugin#8]
Given:
a CI-build of an umbrella project Blargh, with multiple sub-projects Blargh1, Blargh2, etc.
When selenium tests are failing on some sub-project Blargh1, a message is signaled to stdout [[ATTACHMENT|%absolute_path%]]
The Problem:
The screenshot gets published under
jenkins\jobs\Blargh\lastSuccessful\junit-attachments
and the link in the test report on a failed test will not work, because it is pointing to other folder:
%address%/jenkins/job/Blargh/Blargh1/testReport/junit/%testname%/attachments/filename
Workaround:
If you move the attachments folder to jenkins\jobs\Blargh\lastSuccessful\Blargh1\junit-attachments, then the links will work as intended.

Please add the proper support for sub-projects. Thank you.

**Comment by jglick** [comment]
Please use JIRA. This sounds like [JENKINS-19430](https://issues.jenkins-ci.org/browse/JENKINS-19430).
